name: CI - QR Code Generator
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test (generate QR)
        run: |
          python main.py --url https://www.njit.edu --filename ci_smoke.png --silent
          test -f qr_codes/ci_smoke.png

      - name: List outputs
        run: ls -la qr_codes || true
